title: How To Do
description: A collection of useful everyday tools and calculators.
baseurl: "/how-to-do"
url: "https://chaudhary.github.io"

markdown: kramdown
theme: minima

permalink: /blog/:title/

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
