title: How To Do
description: A collection of useful everyday tools and calculators.
baseurl: ""
url: "https://how-to-do.online"

markdown: kramdown
theme: minima

permalink: /blog/:title/

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
